print("------TRAIN TICKET BOOKING------")
name=input("Enter your name :")
sourcecity=input("Enter your starting city")
destination=input("Enter your destination")
date=input("Enter date of your journey in DD/MM/YY")
traino=int(input("Enter your train number :"))
seatno=int(input("Enter your seat number :"))
fare=float(input("Enter your total fare :"))
print("-----BOOKED TICKET-----")
print("Passenger name :",name)
print("Date of journey :",date)
print(sourcecity,destination,sep='-->')
print("Train number :",traino)
print("Seat number :",seatno)
print("Total fare is :",fare)
print("Wish You a Happy Journey!")